### ISSUE TITLE
iOS Xcode problem: no rule to process file

### ISSUE THREAD

**Issue by filipsuk** [mattlewis92/cordova-plugin-is-debug#1]
When I try to compile my ionic2 application in Xcode I get this warning:

```
warning: no rule to process file '/Users/filipsuk/IonicProjects/faviApp/platforms/ios/Favi.cz/Plugins/cordova-plugin-is-debug/IsDebug.h' of type sourcecode.c.h for architecture armv7
warning: no rule to process file '/Users/filipsuk/IonicProjects/faviApp/platforms/ios/Favi.cz/Plugins/cordova-plugin-is-debug/IsDebug.h' of type sourcecode.c.h for architecture arm64
```

And also the plugin does not seem to detect debug mode on ios for me.

My system info:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62

Thanks for the plugin!

**Comment by mattlewis92** [comment]
I think that warning can be safely ignored: http://stackoverflow.com/questions/6509600/compilation-warning-no-rule-to-process-file-for-architecture-i386

Can you share some javascript code that shows how you are using this plugin? It works fine for me on ios.

**Comment by filipsuk** [comment]
For example I want to use GA only in production mode:
```
IsDebug.getIsDebug().then((isDebug: boolean) => {
        if (!isDebug) {
          GoogleAnalytics.startTrackerWithId(AppConfig.GOOGLE_ANALYTICS_ID);
        }
      });
```

This works on Android, not on iOS when running the app from Xcode.

**Comment by mattlewis92** [comment]
That's really odd, I'm using similar code and it works fine for me on ios. I think there's probably a setting in xcode you need to configure to make sure the DEBUG flag is set: http://stackoverflow.com/questions/12499001/xcode-debug-mode-when-is-it-on-off

**Comment by filipsuk** [comment]
I solved it by adding DEBUG=1 under preprocessor macros in xcode (see screenshot). "Build configuration" under scheme was already set to "Debug".
![image](https://cloud.githubusercontent.com/assets/6044955/21350313/f25fb344-c6b6-11e6-9e06-6ba75867d757.png)

**Comment by mattlewis92** [comment]
Nice one, I've updated the readme to point to your comment so it can help other folks 😄

**Comment by joshstrange** [comment]
Is anyone aware of a way to do this programmatically or from the command line? I'd like to avoid opening XCode if at all possible and every time I remove and add back the iOS platform I have to do this. I've tried passed GCC_PREPROCESSOR_DEFINITIONS to xcodebuild but it doesn't seem to honor them (Yes my build-debug.xcconfig has `GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1` in it)
