### ISSUE TITLE
does not compile with phonegap

### ISSUE THREAD

**Issue by badpenguin** [mattlewis92/cordova-plugin-is-debug#3]
I'm getting this error while compiling IOS version with phonegap build:
```
warning: no rule to process file '/project/iHostess 30/Plugins/cordova-plugin-is-debug/IsDebug.h' of type sourcecode.c.h for architecture armv7
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
warning: no rule to process file '/project/iHostess 30/Plugins/cordova-plugin-is-debug/IsDebug.h' of type sourcecode.c.h for architecture arm64
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```

I tried both to set swift-version in config.xml and adding the plugin cordova-plugin-add-swift-support but without luck, still i get the same error. 

Any suggestion?

**Comment by mattlewis92** [comment]
This plugin isn't written in swift, it's in objective C. The messages you're getting are only warnings and not actual errors so shouldn't prevent you from building. I copy pasted the source of this plugin from elsewhere and have little to no native experience, I would recommend re-asking your issue on stackoverflow where you would be able to get a better quality answer. Sorry I couldn't be of more help 😞
